export const vehicleMakesAndModels = [
  {
    "make": "Acura",
    "models": [
      "CSX",
      "ILX",
      "Integra",
      "MDX",
      "NSX",
      "RDX",
      "RL",
      "RLX",
      "TL",
      "TLX",
      "TSX",
      "ZDX"
    ]
  },
  {
    "make": "Alfa Romeo",
    "models": [
      "159",
      "4C",
      "Giulia",
      "Giulietta",
      "Mito",
      "Stelvio",
      "Tonale"
    ]
  },
  {
    "make": "Aston Martin",
    "models": [
      "DB11",
      "DB9",
      "DBS",
      "DBX",
      "DBX707",
      "One-77",
      "Rapide",
      "V12 Vantage",
      "V8 Vantage",
      "Vanquish",
      "Vantage",
      "Virage"
    ]
  },
  {
    "make": "Audi",
    "models": [
      "A1",
      "A3",
      "A3 e-tron",
      "A3 Quattro",
      "A3 Sportback e-tron",
      "A4",
      "A4 allroad",
      "A4 Quattro",
      "A5",
      "A5 Quattro",
      "A5 Sportback",
      "A6",
      "A6 allroad",
      "A6 Quattro",
      "A7",
      "A7 Quattro",
      "A7 Sportback",
      "A8",
      "A8 Quattro",
      "allroad",
      "e-tron GT",
      "e-tron",
      "e-tron S",
      "e-tron S Sportback",
      "e-tron Sportback",
      "Q2",
      "Q2 Quattro",
      "Q3",
      "Q3 Quattro",
      "Q4 e-tron",
      "Q4 e-tron Sportback",
      "Q5",
      "Q5 PHEV",
      "Q5 Sportback",
      "Q7",
      "Q8",
      "R8",
      "RS e-tron GT",
      "RS Q3",
      "RS Q8",
      "RS3",
      "RS5",
      "RS5 Sportback",
      "RS6",
      "RS6 Avant",
      "RS7",
      "RS7 Sportback",
      "S3",
      "S4",
      "S5",
      "S5 Sportback",
      "S6",
      "S7",
      "S7 Sportback",
      "S8",
      "SQ5",
      "SQ5 Sportback",
      "SQ7",
      "SQ8",
      "TT",
      "TT Quattro",
      "TT RS",
      "TT RS Quattro",
      "TTS",
      "TTS Quattro"
    ]
  },
  {
    "make": "BMW",
    "models": [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "ActiveHybrid 3",
      "ActiveHybrid 5",
      "ActiveHybrid 7",
      "Alpina B6 Gran Coupe",
      "Alpina B6 xDrive Gran Coupe",
      "Alpina B7",
      "Alpina B7 xDrive",
      "Alpina B7L",
      "Alpina B7L xDrive",
      "Alpina B8 Gran Coupe",
      "Alpina XB7",
      "i3",
      "i3s",
      "i4",
      "i7",
      "i8",
      "iX",
      "iX xDrive40",
      "iX xDrive50",
      "iX3",
      "M135i",
      "M140i",
      "M2",
      "M235i",
      "M235i xDrive",
      "M235i xDrive Gran Coupe",
      "M240i",
      "M240i xDrive",
      "M3",
      "M340i",
      "M340i xDrive",
      "M4",
      "M440i",
      "M440i Gran Coupe",
      "M440i xDrive",
      "M440i xDrive Gran Coupe",
      "M5",
      "M550i xDrive",
      "M6",
      "M6 Gran Coupe",
      "M760i xDrive",
      "M760Li xDrive",
      "M8",
      "M8 Gran Coupe",
      "M850i xDrive",
      "M850i xDrive Gran Coupe",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4"
    ]
  },
  {
    "make": "Bentley",
    "models": [
      "Azure",
      "Bentayga",
      "Continental",
      "Flying Spur",
      "Mulsanne"
    ]
  },
  {
    "make": "Bugatti",
    "models": [
      "Chiron",
      "Divo",
      "Veyron 16.4"
    ]
  },
  {
    "make": "Buick",
    "models": [
      "Allure",
      "Cascada",
      "Enclave",
      "Enclave Avenir",
      "Encore",
      "Encore GX",
      "Envision",
      "LaCrosse",
      "Lucerne",
      "Regal",
      "Regal Sportback",
      "Regal TourX",
      "Verano"
    ]
  },
  {
    "make": "Cadillac",
    "models": [
      "ATS",
      "CT4",
      "CT5",
      "CT6",
      "CTS",
      "DTS",
      "ELR",
      "Escalade",
      "Escalade ESV",
      "Escalade EXT",
      "LYRIQ",
      "SRX",
      "STS",
      "XT4",
      "XT5",
      "XT6",
      "XTS"
    ]
  },
  {
    "make": "Chevrolet",
    "models": [
      "Avalanche",
      "Aveo",
      "Aveo5",
      "Beat",
      "Blazer",
      "Bolt EUV",
      "Bolt EV",
      "Camaro",
      "Caprice",
      "Captiva",
      "Captiva Sport",
      "Cavalier",
      "Chevy",
      "Cheyenne",
      "City Express",
      "Cobalt",
      "Colorado",
      "Corvette",
      "Cruze",
      "Cruze Limited",
      "Cruze NG",
      "Equinox",
      "Express 1500",
      "Express 2500",
      "Express 3500",
      "Express 4500",
      "Express Cargo",
      "Express Pasajeros",
      "Groove",
      "HHR",
      "Impala",
      "Impala Limited",
      "LCF 3500",
      "LCF 3500HD",
      "LCF 4500",
      "LCF 4500HD",
      "LCF 4500XD",
      "LCF 5500HD",
      "LCF 5500XD",
      "LCF 6500XD",
      "Malibu",
      "Malibu Limited",
      "Matiz",
      "Nuevo Aveo",
      "Onix",
      "Optra",
      "Orlando",
      "S10",
      "Silverado",
      "Sonic",
      "Spark",
      "Spark Classic",
      "Spark EV",
      "SS",
      "Suburban",
      "Suburban 1500",
      "Suburban 2500",
      "Suburban 3500 HD",
      "Tahoe",
      "Tornado",
      "Tornado Van",
      "Tracker",
      "Trailblazer",
      "Traverse",
      "Trax",
      "Volt",
      "W4500 Tiltmaster",
      "W5500 Tiltmaster"
    ]
  },
  {
    "make": "Chrysler",
    "models": [
      "200",
      "300",
      "Cirrus",
      "Grand Caravan",
      "Pacifica",
      "PT Cruiser",
      "Sebring",
      "Town & Country",
      "Voyager"
    ]
  },
  {
    "make": "Dodge",
    "models": [
      "Atos",
      "Attitude",
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Dakota",
      "Dart",
      "Durango",
      "H100",
      "H100 Van",
      "Hornet",
      "i10",
      "Journey",
      "Neon",
      "Nitro",
      "Ram 1500",
      "Ram 2500",
      "Ram 3500",
      "Ram 4000",
      "Ram 4500",
      "Ram 5500",
      "Viper",
      "Vision"
    ]
  },
  {
    "make": "Ferrari",
    "models": [
      "296 GTB",
      "458 Italia",
      "458 Speciale",
      "458 Spider",
      "488 GTB",
      "488 Pista",
      "488 Pista Spider",
      "488 Spider",
      "599 GTB",
      "599 GTO",
      "612 Scaglietti",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "F12 Berlinetta",
      "F12tdf",
      "F8 Spider",
      "F8 Tributo",
      "FF",
      "GTC4Lusso",
      "GTC4Lusso T",
      "LaFerrari",
      "Portofino",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale"
    ]
  },
  {
    "make": "Fiat",
    "models": [
      "124 Spider",
      "500",
      "500C",
      "500E",
      "500L",
      "500X",
      "Albea",
      "Argo",
      "Ducato",
      "JOLLY",
      "Linea",
      "Mobi",
      "Palio",
      "Panda",
      "Punto",
      "Strada",
      "Uno"
    ]
  },
  {
    "make": "Fisker",
    "models": [
      "Karma",
      "OCEAN"
    ]
  },
  {
    "make": "Ford",
    "models": [
      "Bronco",
      "Bronco Sport",
      "C-Max",
      "Courier",
      "Crown Victoria",
      "E-150",
      "E-250",
      "E-350 Super Duty",
      "E-450 Super Duty",
      "E-Transit",
      "Econoline Van",
      "Econoline Wagon",
      "EcoSport",
      "Edge",
      "Escape",
      "Expedition",
      "Explorer",
      "Explorer Sport Trac",
      "F-150",
      "F-150 Lightning",
      "F-250",
      "F-250 Super Duty",
      "F-350",
      "F-350 Super Duty",
      "F-450",
      "F-450 Super Duty",
      "F-550 Super Duty",
      "F-600 Super Duty",
      "F53",
      "F59",
      "F650",
      "F750",
      "Fiesta",
      "Fiesta Ikon",
      "Figo",
      "Flex",
      "Focus",
      "Fusion",
      "GT",
      "LCF",
      "Lobo",
      "Maverick",
      "Mustang",
      "Mustang Mach-E",
      "Police Interceptor Sedan",
      "Police Interceptor Utility",
      "Police Responder Hybrid",
      "Ranger",
      "SHELBY",
      "Special Service Police Sedan",
      "SSV Plug-In Hybrid",
      "Taurus",
      "Transit",
      "Transit Connect",
      "Transit Courier",
      "Transit Custom",
      "Transit-150",
      "Transit-250",
      "Transit-350",
      "Transit-350 HD"
    ]
  },
  {
    "make": "GMC",
    "models": [
      "Acadia",
      "Acadia Limited",
      "Canyon",
      "Hummer EV",
      "Savana",
      "Savana 1500",
      "Savana 2500",
      "Savana 3500",
      "Savana 4500",
      "Sierra",
      "Sierra 1500",
      "Sierra 1500 Limited",
      "Sierra 2500 HD",
      "Sierra 3500 HD",
      "Terrain",
      "W4500 Forward",
      "W5500 Forward",
      "Yukon",
      "Yukon XL",
      "Yukon XL 1500",
      "Yukon XL 2500"
    ]
  },
  {
    "make": "Genesis",
    "models": [
      "G70",
      "G80",
      "G90",
      "GV60",
      "GV70",
      "GV80"
    ]
  },
  {
    "make": "Honda",
    "models": [
      "Accord",
      "Accord Crosstour",
      "BR-V",
      "City",
      "Civic",
      "Clarity",
      "Clarity Plug-In Hybrid",
      "CR-V",
      "CR-Z",
      "Crosstour",
      "Element",
      "Fit",
      "HR-V",
      "Insight",
      "Odyssey",
      "Passport",
      "Pilot",
      "Ridgeline"
    ]
  },
  {
    "make": "Hummer",
    "models": [
      "H3",
      "H3T"
    ]
  },
  {
    "make": "Hyundai",
    "models": [
      "Accent",
      "Azera",
      "Creta",
      "Creta Grand",
      "Elantra",
      "Elantra Coupe",
      "Elantra GT",
      "Elantra N",
      "Entourage",
      "Equus",
      "EX6",
      "EX8",
      "Genesis",
      "Genesis Coupe",
      "Grand i10",
      "H200",
      "H300",
      "H400",
      "H500",
      "HD55",
      "HD65",
      "HD78",
      "Ioniq",
      "Ioniq 5",
      "ix35",
      "Kona",
      "Kona Electric",
      "Kona N",
      "Nexo",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Santa Fe XL",
      "Sonata",
      "Starex",
      "Tucson",
      "Veloster",
      "Veloster N",
      "Venue",
      "Veracruz"
    ]
  },
  {
    "make": "Infiniti",
    "models": [
      "EX35",
      "EX37",
      "FX35",
      "FX37",
      "FX50",
      "G25",
      "G35",
      "G37",
      "JX35",
      "M35",
      "M37",
      "M56",
      "Q40",
      "Q45",
      "Q50",
      "Q60",
      "Q70",
      "QX30",
      "QX4",
      "QX50",
      "QX56",
      "QX60",
      "QX70",
      "QX80"
    ]
  },
  {
    "make": "Isuzu",
    "models": [
      "Ascender",
      "D-Max",
      "i-280",
      "i-290",
      "i-350",
      "i-370",
      "NPR",
      "NPR-HD",
      "NQR",
      "NRR"
    ]
  },
  {
    "make": "Jaguar",
    "models": [
      "E-PACE",
      "F-PACE",
      "F-TYPE",
      "I-PACE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XJ",
      "XJL",
      "XK",
      "XKR"
    ]
  },
  {
    "make": "Jeep",
    "models": [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Cherokee L",
      "Liberty",
      "Patriot",
      "Renegade",
      "Wagoneer",
      "Wrangler",
      "Wrangler Unlimited"
    ]
  },
  {
    "make": "Kia",
    "models": [
      "Bongo",
      "Cadenza",
      "Carnival",
      "Ceed",
      "Cerato",
      "EV6",
      "Forte",
      "Forte Koup",
      "Forte5",
      "K5",
      "K900",
      "Niro",
      "Niro EV",
      "Niro PHEV",
      "Optima",
      "Rio",
      "Rio5",
      "Rondo",
      "Sedona",
      "Seltos",
      "Sorento",
      "Soul",
      "Soul EV",
      "Spectra",
      "Spectra5",
      "Sportage",
      "Stinger",
      "Telluride"
    ]
  },
  {
    "make": "Lamborghini",
    "models": [
      "Aventador",
      "Gallardo",
      "Huracan",
      "Murcielago",
      "Urus"
    ]
  },
  {
    "make": "Land Rover",
    "models": [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Evoque",
      "Freelander 2",
      "LR2",
      "LR3",
      "LR4",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar"
    ]
  },
  {
    "make": "Lexus",
    "models": [
      "CT 200h",
      "ES 250",
      "ES 300",
      "ES 300h",
      "ES 330",
      "ES 350",
      "GS 200t",
      "GS 300",
      "GS 350",
      "GS 430",
      "GS 450h",
      "GS 460",
      "GS F",
      "GX 460",
      "GX 470",
      "HS 250h",
      "IS 200t",
      "IS 250",
      "IS 300",
      "IS 350",
      "IS F",
      "LC 500",
      "LC 500h",
      "LS 430",
      "LS 460",
      "LS 460 L",
      "LS 500",
      "LS 500h",
      "LS 600h L",
      "LX 470",
      "LX 570",
      "LX 600",
      "NX 200t",
      "NX 300",
      "NX 300h",
      "RC 200t",
      "RC 300",
      "RC 350",
      "RC F",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 400h",
      "RX 450h",
      "SC 430",
      "UX 200",
      "UX 250h"
    ]
  },
  {
    "make": "Lincoln",
    "models": [
      "Aviator",
      "Blackwood",
      "Continental",
      "Corsair",
      "LS",
      "Mark LT",
      "MKC",
      "MKS",
      "MKT",
      "MKX",
      "MKZ",
      "Navigator",
      "Navigator L",
      "Nautilus",
      "Town Car",
      "Zephyr"
    ]
  },
  {
    "make": "Lotus",
    "models": [
      "Elise",
      "Evora",
      "Exige"
    ]
  },
  {
    "make": "Lucid",
    "models": [
      "Air"
    ]
  },
  {
    "make": "Maserati",
    "models": [
      "Ghibli",
      "GranTurismo",
      "Levante",
      "Quattroporte"
    ]
  },
  {
    "make": "Maybach",
    "models": [
      "57",
      "57 S",
      "62",
      "62 S"
    ]
  },
  {
    "make": "Mazda",
    "models": [
      "2",
      "3",
      "5",
      "6",
      "626",
      "929",
      "B-Series",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-7",
      "CX-9",
      "Mazda3",
      "Mazda5",
      "Mazda6",
      "MazdaSpeed3",
      "MazdaSpeed6",
      "MAZDA2",
      "MAZDA3",
      "MAZDA6",
      "MX-5 Miata",
      "RX-8",
      "Tribute"
    ]
  },
  {
    "make": "McLaren",
    "models": [
      "540C",
      "570GT",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "765LT",
      "MP4-12C"
    ]
  },
  {
    "make": "Mercedes-Benz",
    "models": [
      "190-Class",
      "A-Class",
      "AMG GT",
      "B-Class",
      "C-Class",
      "CL-Class",
      "CLA-Class",
      "CLK-Class",
      "CLS-Class",
      "E-Class",
      "G-Class",
      "GL-Class",
      "GLA-Class",
      "GLB-Class",
      "GLC-Class",
      "GLE-Class",
      "GLK-Class",
      "GLS-Class",
      "M-Class",
      "Maybach",
      "Metris",
      "R-Class",
      "S-Class",
      "SL-Class",
      "SLK-Class",
      "SLR McLaren",
      "SLS AMG",
      "Sprinter",
      "Sprinter 2500",
      "Sprinter 3500"
    ]
  },
  {
    "make": "Mercury",
    "models": [
      "Grand Marquis",
      "Mariner",
      "Milan",
      "Montego",
      "Mountaineer",
      "Sable"
    ]
  },
  {
    "make": "MINI",
    "models": [
      "Clubman",
      "Convertible",
      "Cooper",
      "Countryman",
      "Hardtop",
      "Paceman",
      "Roadster"
    ]
  },
  {
    "make": "Mitsubishi",
    "models": [
      "3000GT",
      "ASX",
      "Diamante",
      "Eclipse",
      "Eclipse Cross",
      "Endeavor",
      "Galant",
      "i-MiEV",
      "Lancer",
      "Lancer Evolution",
      "Mirage",
      "Mirage G4",
      "Montero",
      "Montero Sport",
      "Outlander",
      "Outlander PHEV",
      "Outlander Sport",
      "Pajero",
      "Raider"
    ]
  },
  {
    "make": "Nissan",
    "models": [
      "240SX",
      "300ZX",
      "350Z",
      "370Z",
      "Altima",
      "Armada",
      "Cube",
      "Frontier",
      "GT-R",
      "Juke",
      "Kicks",
      "Leaf",
      "Maxima",
      "Murano",
      "NV200",
      "NV1500",
      "NV2500 HD",
      "NV3500 HD",
      "Pathfinder",
      "Patrol",
      "Quest",
      "Rogue",
      "Rogue Select",
      "Sentra",
      "Titan",
      "Titan XD",
      "Versa",
      "Versa Note",
      "Xterra"
    ]
  },
  {
    "make": "Peugeot",
    "models": [
      "208",
      "3008",
      "308",
      "5008"
    ]
  },
  {
    "make": "Pontiac",
    "models": [
      "G3",
      "G5",
      "G6",
      "G8",
      "Grand Am",
      "Grand Prix",
      "GTO",
      "Solstice",
      "Torrent",
      "Vibe"
    ]
  },
  {
    "make": "Porsche",
    "models": [
      "911",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "Taycan"
    ]
  },
  {
    "make": "RAM",
    "models": [
      "1500",
      "2500",
      "3500",
      "4500",
      "5500",
      "C/V",
      "ProMaster",
      "ProMaster City"
    ]
  },
  {
    "make": "Rolls-Royce",
    "models": [
      "Cullinan",
      "Dawn",
      "Ghost",
      "Phantom",
      "Wraith"
    ]
  },
  {
    "make": "Saab",
    "models": [
      "9-2X",
      "9-3",
      "9-4X",
      "9-5",
      "9-7X"
    ]
  },
  {
    "make": "Saturn",
    "models": [
      "Astra",
      "Aura",
      "Ion",
      "Outlook",
      "Relay",
      "Sky",
      "Vue"
    ]
  },
  {
    "make": "Scion",
    "models": [
      "FR-S",
      "iA",
      "iM",
      "iQ",
      "tC",
      "xA",
      "xB",
      "xD"
    ]
  },
  {
    "make": "smart",
    "models": [
      "fortwo"
    ]
  },
  {
    "make": "Subaru",
    "models": [
      "Ascent",
      "B9 Tribeca",
      "BRZ",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "SVX",
      "Tribeca",
      "WRX",
      "XV Crosstrek"
    ]
  },
  {
    "make": "Suzuki",
    "models": [
      "Aerio",
      "Equator",
      "Forenza",
      "Grand Vitara",
      "Kizashi",
      "Reno",
      "SX4",
      "Swift",
      "Verona",
      "Vitara",
      "XL-7"
    ]
  },
  {
    "make": "Tesla",
    "models": [
      "Model 3",
      "Model S",
      "Model X",
      "Model Y",
      "Roadster"
    ]
  },
  {
    "make": "Toyota",
    "models": [
      "4Runner",
      "86",
      "Avalon",
      "Avanza",
      "Camry",
      "C-HR",
      "Corolla",
      "Corolla Cross",
      "Corolla iM",
      "Echo",
      "FJ Cruiser",
      "GR Supra",
      "Highlander",
      "Land Cruiser",
      "Matrix",
      "Mirai",
      "Prius",
      "Prius c",
      "Prius Prime",
      "Prius v",
      "RAV4",
      "RAV4 Prime",
      "Sequoia",
      "Sienna",
      "Solara",
      "Tacoma",
      "Tundra",
      "Venza",
      "Yaris",
      "Yaris iA"
    ]
  },
  {
    "make": "Volkswagen",
    "models": [
      "Arteon",
      "Atlas",
      "Atlas Cross Sport",
      "Beetle",
      "CC",
      "Crafter",
      "Eos",
      "Golf",
      "Golf Alltrack",
      "Golf GTI",
      "Golf R",
      "Golf SportWagen",
      "ID.4",
      "Jetta",
      "Jetta GLI",
      "Passat",
      "Phaeton",
      "Rabbit",
      "Routan",
      "Taos",
      "Tiguan",
      "Touareg"
    ]
  },
  {
    "make": "Volvo",
    "models": [
      "C30",
      "C70",
      "S40",
      "S60",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90"
    ]
  }
];